workflows:
  ditonton:
    name: Unit Testing for Application Ditonton
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Installing dependencies
        script: flutter pub get
      - name: Testing for Modularization core
        working_directory: core
        script: flutter test --machine
      - name: Testing for Modularization search
        working_directory: search
        script: flutter test --machine
      - name: Testing for Modularization movies
        working_directory: movies
        script: flutter test --machine
      - name: Testing for Modularization tv_series
        working_directory: tv_series
        script: flutter test --machine
      - name: Testing for Modularization watchlist
        working_directory: watchlist
        script: flutter test --machine
      - name: Building Android
        script: flutter build appbundle --release
      - name: Building Ios
        script: flutter build ios --release --no-codesign
    artifacts: 
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
    publishing: 
      email: 
        recipients:
          - habiyanlazuard21@gmail.com
    triggering:
      events:
        - push