workflows:
  ditonton:
    name: Unit Testing for Application Ditonton
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Installing dependencies
        script: flutter pub get
      - name: Testing for Modularization core
        working_directory: core
        script: flutter test --machine
      - name: Testing for Modularization search
        working_directory: search
        script: flutter test --machine
      - name: Testing for Modularization movies
        working_directory: movies
        script: flutter test --machine
      - name: Building Android
        script: flutter build appbundle --release
      - name: Building Ios
        script: flutter build ios --release --no-codesign
      - name: Zipping AAB file
        script: |
          mkdir -p build/outputs
          cp build/app/outputs/bundle/release/app.aab build/outputs/runner.aap
          zip -r build/outputs/runner.aap.zip build/outputs/runner.aap
    artifacts: 
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/runner.aap.zip
    publishing: 
      email: 
        recipients:
          - habiyanlazuard21@gmail.com
    triggering:
      events:
        - push